theme: jekyll-theme-hacker
title: Renan Almeida's Portfolio
description: Welcome to my portfolio. 
url: "https://renan-alm.github.io"
permalink: /:categories/:year/:month/:day/:title.html

author:
  name: Renan Almeida
  email: renan-alm@github.com

nav:
  - home: /
  - about: /about
  - contact: /contact

social:
  twitter: eng-renan
  github: renan-alm
  linkedin: renan-almeida-93501621

plugins:
  - jekyll-feed
  - jekyll-seo-tag
