# theme: jekyll-theme-hacker
# theme: just-the-docs
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
title: Renan Almeida
description: Welcome to my GitHub Page 
url: "https://renan-alm.github.io"
permalink: /:categories/:year/:month/:day/:title.html

show_downloads: true

aux_links:
  Template Repository: https://github.com/renan-alm/renan-alm.github.io

author:
  name: Renan Almeida
  email: renan-alm@github.com

nav:
  - home: /
  - about: /about
  - contact: /contact

social:
  twitter: eng-renan
  github: renan-alm
  linkedin: renan-almeida-93501621

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-default-layout
